script: |
  cd /home/ubuntu/location-tracking-system
  git fetch origin
  git checkout ci-cd-deploy
  git pull origin ci-cd-deploy
  cd disenop2web
  npm install
  npm run build
  sudo systemctl restart vite-preview
